name = "markdowner-final"
main = "src/index.ts"
compatibility_date = "2025-06-01"
compatibility_flags = [ "nodejs_compat"]


# Browser Rendering API binding
browser = { binding = "MYBROWSER" }

[[durable_objects.bindings]]
name = "BROWSER"
class_name = "Browser"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Browser"] # Array of new classes

[[kv_namespaces]]
binding = "md_cache"
id = "037faf1daed8421e817ba9fdfe6de5fb"

[[unsafe.bindings]]
name = "RATELIMITER"
type = "ratelimit"
namespace_id = "1002"
simple = { limit = 10, period = 60 } # 10 requests per 60 seconds

[ai]
binding = "AI"
model = "@cf/qwen/qwen1.5-14b-chat-awq"

routes = [
	{ pattern = "snapscrape.jyothepro.com", custom_domain = true }
]
